### ISSUE TITLE
Build stage shows no steps and hangs after environment variable CI is set globally

### ISSUE THREAD

**Issue by tatsuyafujisaki** [jenkins-docs/creating-a-pipeline-in-blue-ocean#19]
I have a quesiton about the tutorial (https://jenkins.io/doc/tutorials/create-a-pipeline-in-blue-ocean) that uses this repoistory.

After setting the environment variable CI (= true) globally in the "Follow up" section, the Build stage shows no steps, and never transitions to the Test stage in the UI of Blue Ocean.
<img width="1596" alt="screenshot1" src="https://user-images.githubusercontent.com/1838962/62136127-6a943780-b31e-11e9-86e7-8d57b89105a1.png">

Is it an expected behavior or am I missing something?

**Comment by Shrinathbcone** [comment]
Hi,

I am also observing this behavior. 

Have checked the Jenkinsfile syntax which looks good. Also this is coming when I was aborting step.

Please let me know is there any bug or workaround for this issue.

![image](https://user-images.githubusercontent.com/51479936/68388134-f6bbc380-0185-11ea-922f-b30594f8e4b9.png)
